Repository SeangDev/Team-Presentation, pull requests merged in 2024-03, with the labels that each got.

#6 feature_issue3 : Change the value N to 3
  main.py
Labels: feature

#16 Change input N and return funcyion n+5
  main.py
Labels: feature

#18 Feature/issue7
  main.py
Labels: feature

#19 feature_issue13: Change N to 123 and return to n+321
  main.py
Labels: feature

#20 add edit 1
  readme.txt
Labels: feature

#23 edit 3
  readme.txt
Labels: bugfix

#26 Develop
  readme.txt
Labels: QA

#27 Hotfix/1.1
  readme.txt
Labels: Hotfix

#28 merge from develop to main (hotfix)
  readme.txt
Labels: Hotfix

#30 Change the value a to 32 and b to 76
  test3.py
Labels: feature

#31 feature_newissue24: Change value a to 92, b to 782.
  test2.py
Labels: feature

#38 change a to 38
  test3.py
Labels: feature

#37 feature_issue35: Change a to 2, b to 1
  test5.py
Labels: feature
